var largestSymbols = [
{"symbol": "icudt46_dat", "type": "read-only data", "location": "third_party/icu/source/common/wintz.c", "size": "5.6m"},
{"symbol": "v8::internal::Snapshot::data_", "type": "read-only data", "location": "out_android_arm/Release/obj/v8/tools/gyp/v8_snapshot.gen/snapshot.cc", "size": "606.6k"},
{"symbol": "v8::internal::sources", "type": "read-only data", "location": "out_android_arm/Release/gen/libraries.cc", "size": "303.3k"},
{"symbol": "Perfect_Hash::FindDomain(char const*, unsigned int)::lookup", "type": "read-only data", "location": "net/base/registry_controlled_domains/registry_controlled_domain.cc", "size": "246.9k"},
{"symbol": "InjectedScriptCanvasModuleSource_js", "type": "read-only data", "location": "third_party/WebKit/Source/core/frame/animation/CSSPropertyAnimation.cpp", "size": "144.5k"},
{"symbol": "i18n::phonenumbers::(anonymous namespace)::data", "type": "read-only data", "location": "content/renderer/p2p/socket_dispatcher.cc", "size": "143.5k"},
{"symbol": "stringpool_contents", "type": "read-only data", "location": "net/base/registry_controlled_domains/registry_controlled_domain.cc", "size": "78.9k"},
{"symbol": "webrtc::VideoProcessing::colorTable", "type": "read-only data", "location": "third_party/libjingle/source/talk/media/webrtc/webrtcvoiceengine.cc", "size": "65.5k"},
{"symbol": "ft_adobe_glyph_list", "type": "read-only data", "location": "psnames.c", "size": "56.0k"},
{"symbol": "Perfect_Hash::FindDomain(char const*, unsigned int)::wordlist", "type": "read-only data", "location": "net/base/registry_controlled_domains/registry_controlled_domain.cc", "size": "50.0k"},
{"symbol": "InjectedScriptSource_js", "type": "read-only data", "location": "third_party/WebKit/Source/core/frame/animation/CSSPropertyAnimation.cpp", "size": "49.9k"},
{"symbol": "v8::internal::Snapshot::context_data_", "type": "read-only data", "location": "out_android_arm/Release/obj/v8/tools/gyp/v8_snapshot.gen/snapshot.cc", "size": "49.2k"},
{"symbol": "propsVectorsTrie_index", "type": "read-only data", "location": "third_party/icu/source/common/uchar.c", "size": "44.8k"},
{"symbol": "webrtc::kAvgFECRecoveryXOR", "type": "read-only data", "location": "third_party/webrtc/modules/audio_coding/neteq4/random_vector.cc", "size": "38.7k"},
{"symbol": "WebCore::(anonymous namespace)::staticEntityTable", "type": "data", "location": "out_android_arm/Release/gen/blink/HTMLEntityTable.cpp", "size": "35.7k"},
{"symbol": "v8::internal::sources", "type": "read-only data", "location": "out_android_arm/Release/gen/experimental-libraries.cc", "size": "35.7k"},
{"symbol": "propsTrie_index", "type": "read-only data", "location": "third_party/icu/source/common/uchar.c", "size": "34.4k"},
{"symbol": "armSP_FFT_F32TwiddleTable", "type": "read-only data", "location": "third_party/openmax_dl/dl/sp/src/armSP_FFT_F32TwiddleTable.c", "size": "32.8k"},
{"symbol": "gInvSqrtTable", "type": "read-only data", "location": "third_party/skia/src/effects/SkEmbossMask.cpp", "size": "32.8k"},
{"symbol": "net::kPreloadedSTS", "type": "data", "location": "net/http/transport_security_state.cc", "size": "28.7k"},
{"symbol": "WebCore::CSSComputedStyleDeclaration::getPropertyCSSValue(WebCore::CSSPropertyID, WebCore::EUpdateLayout) const", "type": "code", "location": "third_party/WebKit/Source/core/css/CSSComputedStyleDeclaration.cpp", "size": "26.9k"},
{"symbol": "WebCore::CSSValueKeywordsHash::findValueImpl(char const*, unsigned int)::lookup", "type": "read-only data", "location": "out_android_arm/Release/gen/blink/CSSValueKeywords.cpp", "size": "25.0k"},
{"symbol": "InspectorOverlayPage_html", "type": "read-only data", "location": "third_party/WebKit/Source/core/inspector/InspectorDOMAgent.cpp", "size": "22.9k"},
{"symbol": "nid_objs", "type": "data", "location": "third_party/openssl/openssl/crypto/objects/obj_dat.c", "size": "22.1k"},
{"symbol": "v8::internal::Counters::Counters(v8::internal::Isolate*)", "type": "code", "location": "v8/src/v8-counters.cc", "size": "21.8k"},
{"symbol": "disk_cache::BackendImpl::ReportStats()", "type": "code", "location": "net/disk_cache/backend_impl.cc", "size": "20.5k"},
{"symbol": "ubidi_props_trieIndex", "type": "read-only data", "location": "third_party/icu/source/common/ubidi_props.c", "size": "19.8k"},
{"symbol": "sqlite3VdbeExec", "type": "code", "location": "third_party/sqlite/amalgamation/sqlite3.c", "size": "19.5k"},
{"symbol": "WebCore::V8WindowAttributes", "type": "data", "location": "out_android_arm/Release/gen/blink/bindings/V8DerivedSources14.cpp", "size": "19.2k"},
{"symbol": "WebCore::HTMLNames::init()", "type": "code", "location": "out_android_arm/Release/gen/blink/HTMLNames.cpp", "size": "19.0k"},
{"symbol": "ucase_props_trieIndex", "type": "read-only data", "location": "third_party/icu/source/common/ucase.c", "size": "18.7k"},
{"symbol": "propsVectors", "type": "read-only data", "location": "third_party/icu/source/common/uchar.c", "size": "18.5k"},
{"symbol": "WebCore::HTMLTokenizer::nextToken(WebCore::SegmentedString&, WebCore::HTMLToken&)", "type": "code", "location": "third_party/WebKit/Source/core/html/parser/HTMLTokenizer.cpp", "size": "18.3k"},
{"symbol": "WebCore::htmlUserAgentStyleSheet", "type": "read-only data", "location": "out_android_arm/Release/gen/blink/CSSValueKeywords.cpp", "size": "18.3k"},
{"symbol": "encode_mcu_huff", "type": "code", "location": "third_party/libjpeg_turbo/jchuff.c", "size": "17.8k"},
{"symbol": "v8::internal::Heap::CheckpointObjectStats()", "type": "code", "location": "v8/src/heap.cc", "size": "16.7k"},
{"symbol": "dct_value_tokens", "type": "read-only data", "location": "tokenize.c", "size": "16.4k"},
{"symbol": "_indic_syllable_machine_indicies", "type": "read-only data", "location": "third_party/harfbuzz-ng/src/hb-ot-shape-complex-indic.cc", "size": "16.2k"},
{"symbol": "yyparse(TParseContext*)", "type": "code", "location": "third_party/angle/src/compiler/glslang_tab.cpp", "size": "15.8k"},
{"symbol": "WebCore::CSSPropertyAnimation::ensurePropertyMap() [clone .part.142]", "type": "code", "location": "third_party/WebKit/Source/core/frame/animation/CSSPropertyAnimation.cpp", "size": "15.4k"},
{"symbol": "gpu::kSoftwareRenderingListJson", "type": "read-only data", "location": "third_party/re2/util/stringpiece.cc", "size": "15.0k"},
{"symbol": "DebuggerScriptSource_js", "type": "read-only data", "location": "third_party/WebKit/Source/bindings/v8/NPV8Object.cpp", "size": "14.6k"},
{"symbol": "v8::internal::TrigonometricLookupTable::kSinTable", "type": "read-only data", "location": "out_android_arm/Release/gen/trig-table.cc", "size": "14.4k"},
{"symbol": "v8::internal::TrigonometricLookupTable::kCosXIntervalTable", "type": "read-only data", "location": "out_android_arm/Release/gen/trig-table.cc", "size": "14.4k"},
{"symbol": "XMLViewer_js", "type": "read-only data", "location": "third_party/WebKit/Source/core/workers/WorkerObjectProxy.cpp", "size": "14.0k"},
{"symbol": "WebCore::SVGNames::init()", "type": "code", "location": "out_android_arm/Release/gen/blink/SVGNames.cpp", "size": "12.8k"},
{"symbol": "sctp_setopt", "type": "code", "location": "third_party/usrsctp/usrsctplib/netinet/sctp_usrreq.c", "size": "12.7k"},
{"symbol": "v8::internal::StatisticsExtension::GetCounters(v8::FunctionCallbackInfo<v8::Value> const&)", "type": "code", "location": "v8/src/extensions/statistics-extension.cc", "size": "11.6k"},
{"symbol": "WebCore::lookup", "type": "read-only data", "location": "out_android_arm/Release/gen/blink/CSSPropertyNames.cpp", "size": "11.4k"},
{"symbol": "gpu::kGpuDriverBugListJson", "type": "read-only data", "location": "third_party/re2/util/stringpiece.cc", "size": "11.1k"},
{"symbol": "net::NetLogLogger::GetConstants()", "type": "code", "location": "net/base/net_log_logger.cc", "size": "11.0k"},
{"symbol": "v8::internal::kIntrinsicFunctions", "type": "data", "location": "runtime.cc", "size": "10.9k"},
{"symbol": "sqlite3Parser", "type": "code", "location": "third_party/sqlite/amalgamation/sqlite3.c", "size": "10.6k"},
{"symbol": "cssyyparse(WebCore::BisonCSSParser*)", "type": "code", "location": "/usr/local/google/code/out_android_arm/Release/gen/blink/CSSGrammar.cpp", "size": "10.5k"},
{"symbol": "WebCore::StyleBuilder::applyProperty(WebCore::CSSPropertyID, WebCore::StyleResolverState&, WebCore::CSSValue*, bool, bool)", "type": "code", "location": "out_android_arm/Release/gen/blink/StyleBuilder.cpp", "size": "9.7k"},
{"symbol": "WebCore::nameToPseudoTypeMap()", "type": "code", "location": "third_party/WebKit/Source/core/css/CSSSelector.cpp", "size": "9.3k"},
{"symbol": "vp8_get_compressed_data", "type": "code", "location": "third_party/libvpx/source/libvpx/vp8/encoder/onyx_if.c", "size": "9.0k"},
{"symbol": "icu_46::RegexMatcher::MatchAt(long long, signed char, UErrorCode&)", "type": "code", "location": "third_party/icu/source/i18n/rematch.cpp", "size": "8.9k"},
{"symbol": "WebTestRunner::TestRunner::TestRunner(WebTestRunner::TestInterfaces*)", "type": "code", "location": "content/shell/renderer/test_runner/TestRunner.cpp", "size": "8.9k"},
{"symbol": "indic_table", "type": "read-only data", "location": "third_party/harfbuzz-ng/src/hb-ot-shape-complex-indic-table.cc", "size": "8.8k"},
{"symbol": "WebCore::BisonCSSParser::parseValue(WebCore::CSSPropertyID, bool) [clone .part.358]", "type": "code", "location": "out_android_arm/Release/gen/blink/BisonCSSParser.cpp", "size": "8.8k"},
{"symbol": "WebCore::AnimatedStyleBuilder::applyProperty(WebCore::CSSPropertyID, WebCore::StyleResolverState&, WebCore::AnimatableValue const*)", "type": "code", "location": "third_party/WebKit/Source/core/css/resolver/AnimatedStyleBuilder.cpp", "size": "8.7k"},
{"symbol": "sctp_process_control", "type": "code", "location": "third_party/usrsctp/usrsctplib/netinet/sctp_input.c", "size": "8.7k"},
{"symbol": "WebCore::valueListStringPool", "type": "read-only data", "location": "out_android_arm/Release/gen/blink/CSSValueKeywords.cpp", "size": "8.6k"},
{"symbol": "WebCore::stringpool_contents", "type": "read-only data", "location": "out_android_arm/Release/gen/blink/CSSValueKeywords.cpp", "size": "8.6k"},
{"symbol": "WebCore::EventTypeNames::init()", "type": "code", "location": "out_android_arm/Release/gen/blink/EventTypeNames.cpp", "size": "8.5k"},
{"symbol": "net::HistogramWatcher::OnConnectionTypeChanged(net::NetworkChangeNotifier::ConnectionType)", "type": "code", "location": "net/base/network_change_notifier.cc", "size": "8.4k"},
{"symbol": "disk_cache::BackendImpl::FirstEviction()", "type": "code", "location": "net/disk_cache/backend_impl.cc", "size": "8.3k"},
{"symbol": "WebCore::stringpool_contents", "type": "read-only data", "location": "out_android_arm/Release/gen/blink/CSSPropertyNames.cpp", "size": "8.3k"},
{"symbol": "WebCore::lookupHTMLTag(unsigned short const*, unsigned int)", "type": "code", "location": "out_android_arm/Release/gen/blink/HTMLElementLookupTrie.cpp", "size": "8.3k"},
{"symbol": "content::RenderViewImpl::OnMessageReceived(IPC::Message const&)", "type": "code", "location": "content/renderer/render_view_impl.cc", "size": "8.2k"},
{"symbol": "TT_RunIns", "type": "code", "location": "third_party/freetype/src/truetype/ttinterp.c", "size": "8.2k"},
{"symbol": "crc_table", "type": "read-only data", "location": "third_party/zlib/crc32.c", "size": "8.2k"},
{"symbol": "dct_value_cost", "type": "read-only data", "location": "tokenize.c", "size": "8.2k"},
{"symbol": "kCoefficientsRgbY", "type": "read-only data", "location": "media/base/simd/yuv_to_rgb_table.cc", "size": "8.2k"},
{"symbol": "celt_encode_with_ec", "type": "code", "location": "third_party/opus/src/celt/celt_encoder.c", "size": "8.2k"},
{"symbol": "unibrow::kEcma262UnCanonicalizeMultiStrings0", "type": "read-only data", "location": "v8/src/unicode.cc", "size": "8.0k"},
{"symbol": "unibrow::kEcma262UnCanonicalizeTable0", "type": "read-only data", "location": "v8/src/unicode.cc", "size": "7.9k"},
{"symbol": "yylex(YYSTYPE*, TSourceLoc*, void*)", "type": "code", "location": "out_android_arm/Release/glslang_lex.cpp", "size": "7.8k"},
{"symbol": "icu_46::RegexMatcher::MatchChunkAt(int, signed char, UErrorCode&)", "type": "code", "location": "third_party/icu/source/i18n/rematch.cpp", "size": "7.7k"},
{"symbol": "WebCore::mediaControlsUserAgentStyleSheet", "type": "read-only data", "location": "out_android_arm/Release/gen/blink/CSSValueKeywords.cpp", "size": "7.6k"},
{"symbol": "WebCore::propertyNameStringsPool", "type": "read-only data", "location": "out_android_arm/Release/gen/blink/CSSPropertyNames.cpp", "size": "7.6k"},
{"symbol": "gpu::GpuControlList::GpuControlListEntry::GetEntryFromValue(base::DictionaryValue const*, bool, std::hash_map<std::string, int, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, int> > > const&, bool)", "type": "code", "location": "gpu/config/gpu_control_list.cc", "size": "7.5k"},
{"symbol": "sqlite3Select", "type": "code", "location": "third_party/sqlite/amalgamation/sqlite3.c", "size": "7.5k"},
{"symbol": "sh::OutputHLSL::visitAggregate(Visit, TIntermAggregate*)", "type": "code", "location": "third_party/angle/src/compiler/OutputHLSL.cpp", "size": "7.4k"},
{"symbol": "sctp_handle_sack", "type": "code", "location": "third_party/usrsctp/usrsctplib/netinet/sctp_indata.c", "size": "7.3k"},
{"symbol": "sctp_lower_sosend", "type": "code", "location": "third_party/usrsctp/usrsctplib/netinet/sctp_output.c", "size": "7.1k"},
{"symbol": "gfx::GetMockGLProcAddress(char const*)", "type": "code", "location": "out_android_arm/Release/gen/ui/gl/gl_bindings_autogen_mock.cc", "size": "6.9k"},
{"symbol": "opus_encode_native", "type": "code", "location": "third_party/opus/src/src/opus_encoder.c", "size": "6.9k"},
{"symbol": "void cc::CalculateDrawPropertiesInternal<cc::LayerImpl>(cc::LayerImpl*, cc::SubtreeGlobals<cc::LayerImpl> const&, cc::DataForRecursion<cc::LayerImpl> const&, cc::LayerImpl::RenderSurfaceListType*, cc::LayerImpl::RenderSurfaceListType*, std::vector<cc::AccumulatedSurfaceState<cc::LayerImpl>, std::allocator<cc::AccumulatedSurfaceState<cc::LayerImpl> > >*) [clone .constprop.217]", "type": "code", "location": "cc/trees/layer_tree_host_common.cc", "size": "6.8k"},
{"symbol": "sctp_process_data", "type": "code", "location": "third_party/usrsctp/usrsctplib/netinet/sctp_indata.c", "size": "6.8k"},
{"symbol": "WebCore::StyleBuilder::oldApplyProperty(WebCore::CSSPropertyID, WebCore::StyleResolverState&, WebCore::CSSValue*, bool, bool)", "type": "code", "location": "third_party/WebKit/Source/core/css/resolver/StyleBuilderCustom.cpp", "size": "6.8k"},
{"symbol": "void cc::CalculateDrawPropertiesInternal<cc::Layer>(cc::Layer*, cc::SubtreeGlobals<cc::Layer> const&, cc::DataForRecursion<cc::Layer> const&, cc::Layer::RenderSurfaceListType*, cc::Layer::RenderSurfaceListType*, std::vector<cc::AccumulatedSurfaceState<cc::Layer>, std::allocator<cc::AccumulatedSurfaceState<cc::Layer> > >*) [clone .constprop.215]", "type": "code", "location": "cc/trees/layer_tree_host_common.cc", "size": "6.8k"},
{"symbol": "sqlite3Pragma", "type": "code", "location": "third_party/sqlite/amalgamation/sqlite3.c", "size": "6.6k"},
{"symbol": "webrtc::kCodeRateXORTable", "type": "read-only data", "location": "third_party/webrtc/modules/video_coding/main/source/media_opt_util.cc", "size": "6.5k"},
{"symbol": "v8::internal::(anonymous namespace)::flags", "type": "data", "location": "flags.cc", "size": "6.4k"},
{"symbol": "disk_cache::EntryImpl::ReportIOTime(disk_cache::EntryImpl::Operation, base::TimeTicks const&)", "type": "code", "location": "net/disk_cache/entry_impl.cc", "size": "6.4k"},
{"symbol": "v8::internal::ExternalReferenceTable::PopulateTable(v8::internal::Isolate*)::ref_table", "type": "data", "location": "v8/src/serialize.cc", "size": "6.4k"},
{"symbol": "disk_cache::BackendImpl::OpenEntryImpl(std::string const&)", "type": "code", "location": "net/disk_cache/backend_impl.cc", "size": "6.3k"},
{"symbol": "void WebCore::CSSTokenizer::detectAtToken<unsigned short>(int, bool)", "type": "code", "location": "out_android_arm/Release/gen/blink/CSSTokenizer.cpp", "size": "6.2k"},
];
